### ISSUE TITLE
searx preferences completely freezes rose

### ISSUE THREAD

**Issue by se7en-x230** [mini-rose/rose#11]
building with let's say https://paulgo.lo as a searx instance default homepage works just fine.
once the site is loaded and I try to change the theme of the searx instance to dark rose freezes

**Comment by bellrise** [comment]
I think searx implementation uses cookies for preferences

**Comment by bellrise** [comment]
I think searx uses cookies for saving preferences as shown here in [preferences.py](https://github.com/searx/searx/blob/master/searx/preferences.py#L64):
```py
resp.set_cookie(name, self.value, max_age=COOKIE_MAX_AGE)
```

So i'm guessing it has to do with our cookie implementation, we're wokring on it.

**Comment by bellrise** [comment]
We found the problem, its a problem with webkit itself, which freezes upon item selection in a `<select>` element. We made a bug report to the devs, now we have to wait.

**Comment by fenze** [comment]
At this moment we cannot do anything, we're waiting for response from webkit developers. I will write there update.
