### ISSUE TITLE
Remove x11

### ISSUE THREAD

**Issue by J0hsHH** [mini-rose/rose#15]
is it possible x11 from rose so you can use it on wayland? something that netsurf has and [https://sr.ht/~sircmpwn/visurf/](visurf).
Otherwise i love rose keep up the good work

**Comment by fenze** [comment]
We're going to remove x11 from dependency list, but for now is impossible.

**Comment by bellrise** [comment]
There would be no problems with compiling with GTK under wayland, but the webkit for wayland port seems to be dead.

**Comment by fenze** [comment]
Removed x11 from dependencies, you can try build rose on wayland!
