### ISSUE TITLE
colour of rose program is to bright and tinted purple

### ISSUE THREAD

**Issue by zooki2006** [mini-rose/rose#17]
**Describe the bug**
the colours of websites and inspector 

**Expected behavior**
the colours are as expected

**Screenshots**
![2022-05-26-170830_1920x1080_scrot](https://user-images.githubusercontent.com/55743069/170528728-48a72598-1622-4fe6-aa9e-7433b3b5386d.png)

![2022-05-26-171222_1920x1080_scrot](https://user-images.githubusercontent.com/55743069/170529061-2f758597-41b9-427d-9fba-c91813cec44a.png)
this image bellow is for reference on how those websites look in Firefox
![2022-05-26-171314_1920x1080_scrot](https://user-images.githubusercontent.com/55743069/170529267-9a133e0b-dcba-4dd4-8ba1-ee5a58c09980.png)

**Desktop (please complete the following information):**
 - OS: artix linux
 - webkit2gtk-5.0 2.36.2-1 installed from arch repo
 - gtk4 1:4.6.4-1 installed from artix repo

**Comment by WooxHimself** [comment]
Same issue, leaving my comment there if you get it fixed...

**Comment by zooki2006** [comment]
when running rose with GTK_THEME=Adwaita:dark rose
the tint colour changes so it seems like the tinit comes from your gtk theme?
![2022-05-27-103732_1920x1080_scrot](https://user-images.githubusercontent.com/55743069/170673785-31eb950a-97a7-4dd1-8c2c-4baf6cace56b.png)

**Comment by fenze** [comment]
Is gtk4 bug, you need wait for fix from gnome. Many themes unfortunately not working properly on new gtk :/
