### ISSUE TITLE
Linking error: undefined reference

### ISSUE THREAD

**Issue by NikitaIvanovV** [mini-rose/rose#18]
I cannot build `rose` due to ld error:
```
/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../lib/libjavascriptcoregtk-5.0.so: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../lib/libwebkit2gtk-5.0.so: undefined reference to `std::__glibcxx_assert_fail(char const*, int, char const*, char const*)@GLIBCXX_3.4.30'
collect2: error: ld returned 1 exit status
make: *** [makefile:27: rose] Error 1
```

I'm guessing I miss some library but I don't know which. I also tried to install an AUR package, hoping it would automatically install all the dependencies but it didn't.

**Comment by WooxHimself** [comment]
Have you installed the `webkit2gtk-5.0` package from the AUR?

**Comment by fenze** [comment]
![image](https://user-images.githubusercontent.com/93622468/170820322-a29aedfc-34d7-40e9-94ed-9fe564379f49.png)

**Comment by NikitaIvanovV** [comment]
> Have you installed the `webkit2gtk-5.0` package from the AUR?
@WooxHimself Yes.
