### ISSUE TITLE
Freezing on scroll

### ISSUE THREAD

**Issue by MckinleyX** [mini-rose/rose#22]
**Describe the bug**
Scrolling quickly with laptop touchpad freezes rose. 

**Expected behavior**
Browser should scroll without freezing.

**Desktop:**
 - OS: Arch Linux
 - WebKit: webkit2gtk-5.0 2.36.4-2
 - Gtk gtk4 1:4.6.6-1

**Additional context**
I don't have a physical mouse with me, but rose seems to handle touchscreen scrolling fine,
but not scrolling with the touchpad.

https://user-images.githubusercontent.com/32435060/180493818-8bbb9181-3f52-4fd3-82e3-0860f472b796.mp4

**Comment by fenze** [comment]
Unfortunately is the webkit bug. Try to turn off/turn on "smooth scroll" :/
Ofc I will report the bug to webkit team!

**Comment by fenze** [comment]
Fixed!

https://webkitgtk.org/2022/08/07/webkitgtk2.36.6-released.html
