### ISSUE TITLE
The "Inspect Element" causes the browser to freeze

### ISSUE THREAD

**Issue by rempas** [mini-rose/rose#25]
**Describe the bug**
When I open the `Inspect Element` and click some tabs, the browser becomes unresponsive. While I can still move the cursor, the browser doesn't respond when I click somewhere. Originally, I have found the bug when clicking in the "sources" tab but now it seems that a lot of tabs are giving this result.

**Expected behavior**
To work.

**Screenshots**
In the case of my problem, I don't think screenshots will help in any way so I don't post any.

**Desktop (please complete the following information):**
 - OS: ArcoLinux
 - WebKit: 2.36.5
 - Gtk: 4.6.6

**Comment by fenze** [comment]
Unfortunately that bug is typically webkitgtk's. We can only wait for the developers to do so :/
[Webkitgtk bugs](https://bugs.webkit.org/show_bug.cgi?id=GTK4)
