### ISSUE TITLE
kraut.zone does not render fonts correctly

### ISSUE THREAD

**Issue by rempas** [mini-rose/rose#26]
**Describe the bug**
As shown in the screenshot, the fonts do not render correctly in [kraut.zone](https://kraut.zone/). I have tried some other sites and I the fonts seemed to work correctly. I don't know what's different about this site however...

**Expected behavior**
I suppose to render correctly...

**Screenshots**
![krautzone](https://user-images.githubusercontent.com/60424977/182017828-2cfd56d9-8ff6-47c4-b167-64f4a9911cb8.png)

**Desktop (please complete the following information):**
 - OS: ArcoLinux
 - WebKit: 2.36.5
 - Gtk: 4.6.6

**Comment by fenze** [comment]
Can you give me your resolution?
Try add to rose_webview_new
[font-size-to-points](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#webkit-settings-font-size-to-points) or [font-size-to-pixels](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#webkit-settings-font-size-to-pixels). If one of these will work, please give feedback/pull request. Thanks!

**Comment by rempas** [comment]
My resolution is 1080p. This happens in both floating and full screen windows.

Now about the other functions you pointed out. Where exactly should I place them (and what is "guint32" cause I couldn't find it in the source code of "rose")?

**Comment by fenze** [comment]
Site doesn't include any font. Webkit uses default sans-serif font. You can change default font with [that](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#webkit-settings-set-default-font-family) function. Add after settings definition in `rose_webview_new` 
```c
	settings = webkit_settings_new_with_settings(
		"enable-developer-extras", 1,
		"enable-media-stream", 1,
		"javascript-can-access-clipboard", 1,
		"enable-smooth-scrolling", 1, NULL);

	webkit_settings_set_default_font_family(settings, "your font");
 ```

**Comment by fenze** [comment]
In other case, you need to set sans-serif in fontconfig.
