### ISSUE TITLE
Won't build on Arch Linux | rose-beta doesn't exist

### ISSUE THREAD

**Issue by blank1-Dev** [mini-rose/rose#28]
**What I did**
Executed `yay -Sy rose-browser`

**What I expected**
Rose to install successfully.

**What I got instead**
`==> Starting build()...
/home/blank/.cache/yay/rose-browser/PKGBUILD: line 15: cd: /home/blank/.cache/yay/rose-browser/src/rose-beta: No such file or directory
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: rose-browser`

**What I tried**
- Manually building with makepkg
- Creating a rose-beta directory/renaming the `rose` file to `rose-beta`
- Inspecting the PKGBUILD Manually to see if I can fix.
- Making sure all proper dependencies were installed and up to date.
- Tried building on another computer with fresh install of arch

**Software Information**
Distro: Arch
Kernel: 6.0.8-arch1-1
i3wm gaps
yay v11.3.0.r4.gb6b1888 - libalpm v13.0.2

--
I would love a fix to this as I really like the concept of rose and want to try it out.

**Comment by fenze** [comment]
Im gonna fix it asap, for now try to build from source
