### ISSUE TITLE
Tabs not working

### ISSUE THREAD

**Issue by rice7th** [mini-rose/rose#30]
There is no way to open new tabs inside rose at the moment. There are only options to close and switch tabs.

**Comment by fenze** [comment]
If you in last tab, you can switch to next (by default: alt+l) and you in new tab. You can tweak to create keybind for new tab.

**Comment by rice7th** [comment]
Sorry, but there is no way to create a new tab! There is not even a shortcut in config.h, and there is no documentation whatsoever

**Comment by fenze** [comment]
Added newtab binding in new commit, i will create manpage asap.
