### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by githubisviolatingthegpl** [mini-rose/rose#35]
Greetings,

I would like to suggest using a license like the BSD/MIT/ISC/CC0 or one of the GNU licenses.

Writing your own license is generally not a good idea, if you're not a lawyer. (IANAL)

In particular, the license makes no stipulation that it should be included with the software, so if you wanted to keep this project licensed with the same custom license, the license should probably include a clause about including it with any copy of the software or source.

Not a demand, but an earnest suggestion. Please use a license written by someone with legal expertise. Not doing so could harm the adoption of the project.

Best regards.

(Yes, the username is my commentary on github copoilot, but I'm not a GNU license absolutist. Use the license you like best. Also, IANAL again, but github copilot most likely violates many more licenses than the GPL)

**Comment by NunoSempere** [comment]
I would also appreciate this.

**Comment by fenze** [comment]
Now rose is under MIT license.

**Comment by githubisviolatingthegpl** [comment]
Super, thank you! :)
