### ISSUE TITLE
Running rose without systemd

### ISSUE THREAD

**Issue by MrMineDe** [mini-rose/rose#9]
When i tried to pull the dependencies for rose: gtk4 and webkit2gtk5.0, gtk4 installed just fine, but webkit2gtk5.0 seems to be needing systemd etc as dependency. I'm running artix linux with openrc though and therefor dont have systemd etc. I don't really see why i would need systemd for a browser/webkit anyway lol

I searched for a minimalistic browser for quite a while now and this looks really promising, but it seems like i wont be able to install it without changing distro

So this may be the wrong place to ask, but is there a way to run the browser without systemd?

**Comment by LittleHam** [comment]
I'm running into the same issue as I'm using runit in place of systemd.
This project looks very promising and I would love to take a look at it, but as it stands the only way would be to install systemd which I do not want.

**Comment by fenze** [comment]
Hi! Sure, we will try to make rose operate on all UNIX systems. Could you describe your problem in more detail? I will give a few points that would help us at work!

- the moment when the application does not want to turn on or compile
- exact compiler logs by using "Make Debug"

If the problem concerns individual dependencies, it was best to look for a solution at the source of the problem. This week I will try to find time to install Void Linux on VM and test Rose on it, maybe then we will add detailed instructions on the Wiki project!

**Comment by MrMineDe** [comment]
ty for your help, so i'll try to explain the problem a bit more in detail: I tried to pull the necessary dependencies for rose via pacman. Gtk4 and webkit2gtk5.0.

Pacman throwed an error at me, bc he couldnt get a systemd dependency for webkit, bc those systemd packages obviously conflict with openrc packages. ( webkit2gtk5.0 needs the systemd and other systemd packages as dependencies )

So if i just dont install webkit2gtk5.0 and try to compile anyways gcc throws a bunch of errors at me, bc there are libraries missing ( probably all the webkit libraries )

I dont have the errors in front of me, but i can send then later if you wish. I dont think they will help though, as it just misses a dependency

**Comment by linuxmobile** [comment]
> So this may be the wrong place to ask, but is there a way to run the browser without systemd?

I've got the same. I'm using dinit and can't compile it

**Comment by bellrise** [comment]
We're looking into it, why would webkit need systemd as a dependency. :)

**Comment by fenze** [comment]
Only way is compiling webkit localy. For now we cannot help :/

**Comment by MrMineDe** [comment]
Well how can i compile webkit locally then lol. I cant find any documentation or smth like that for webkit2gtk4.0. I really want to use test this browser so if there's a way, I'll look if i can make it happen. So if there's some kind of documentation for compiling it manually or other resources for it, that you are aware of, would you be able to send it? I couldn't find any.

**Comment by MrMineDe** [comment]
I can also install webkit2gtk-5.0 that way and compile rose, but rose wont open any sites that im trying to open. It just stays white.
